use_gpu: True
device: -1
early_stop:
  patience: 10
seed: 12345
federate:
  mode: standalone
  total_round_num: 1000
  sample_client_rate: 0.1
  client_num: 200
data:
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  batch_size: 32
  subsample: 0.05
  num_workers: 0
  transform: [['ToTensor'], ['Normalize', {'mean': [0.1307], 'std': [0.3081]}]]
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
train:
  local_update_steps: 2
  batch_or_epoch: epoch
  optimizer:
    lr: 0.1
    weight_decay: 0.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 10
  metrics: ['acc', 'correct']
  split: [ 'test', 'val' ]

